# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SROPrint
                                 A QGIS plugin
 SRO PRINT
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-09-22
        copyright            : (C) 2020 by Mathias Mirra
        email                : mmirra@mcgr.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SROPrint class from file SROPrint.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .SRO_PRINT import SROPrint
    return SROPrint(iface)
